server:
  port: 8083

spring:
  application:
    name: order
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: nicusor
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    enabled: true