server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/api/v1/auth/**

        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=/api/v1/products/**

        - id: order
          uri: lb://ORDER
          predicates:
            - Path=/api/v1/orders/**


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  tracing:
#    sampling:
#      probability: 1.0