server:
  port: 8082

spring:
  application:
    name: product
  datasource:
    url: jdbc:postgresql://postgres:5432/product
    username: nicusor
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    enabled: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka