server:
  port: 8084

spring:
  application:
    name: notification
  kafka:
    bootstrap-servers: localhost:9092
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    enabled: true